### ISSUE TITLE
Latin American Spanish is missing (es-419)

### ISSUE THREAD

**Issue by HowlingWolfHWC** [KuromeSan/KitsuneOffline#3]
Yeah... It is missing!

**Comment by LiEnby** [comment]
https://github.com/KuromeSan/KitsuneOffline/blob/master/logos/2020/kitsune/rc6/messages.es-419.nocache.json its here, i just dont want to have to rebuild kitsuneoffline for all those platforms again

**Comment by thecoder08** [comment]
@KuromeSan I have set up some CI/CD using Github Actions. It builds the app for all platforms (apart from mobile). To start using it, go to Pull Requests and merge my one about the CI/CD. Github Actions automatically builds your code whenever you make a change to it, so that you dont have the hassle of going through and building it manually.

**Comment by thecoder08** [comment]
I can create a PR too

**Comment by LiEnby** [comment]
Thanks ^^

**Comment by thecoder08** [comment]
@KuromeSan Now you can create a new release with the CI/CD packages that were generated, and close this issue

**Comment by thecoder08** [comment]
@HowlingWolfHWC you can just download the latest release from the actions tab. It should have Latin American Spanish. Then you can close this issue.
